//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.18 at 01:51:09 AM EEST 
//


package gr.aua.simbug.definition;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Configuration">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="Parameter" type="{}ParameterType"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PlayerChoiceVariables">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="PlayerChoiceVariable" type="{}dataType"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UserStateVariables">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="UserStateVariable" type="{}dataType"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="WorldStateVariables">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="WorldStateVariable" type="{}dataType"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ExternalVariables">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="PlayerChoiceVariable" type="{}ExternalDataType"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RandomNumberGenerators">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="RandomNumberGenerator" type="{}RandomNumberGeneratorType"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ChoicesToStateAlgorithm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "Definitions")
public class Definitions {

    @XmlElement(name = "Configuration", required = true)
    protected Definitions.Configuration configuration;
    @XmlElement(name = "PlayerChoiceVariables", required = true)
    protected Definitions.PlayerChoiceVariables playerChoiceVariables;
    @XmlElement(name = "UserStateVariables", required = true)
    protected Definitions.UserStateVariables userStateVariables;
    @XmlElement(name = "WorldStateVariables", required = true)
    protected Definitions.WorldStateVariables worldStateVariables;
    @XmlElement(name = "ExternalVariables", required = true)
    protected Definitions.ExternalVariables externalVariables;
    @XmlElement(name = "RandomNumberGenerators", required = true)
    protected Definitions.RandomNumberGenerators randomNumberGenerators;
    @XmlElement(name = "ChoicesToStateAlgorithm", required = true)
    protected String choicesToStateAlgorithm;

    /**
     * Gets the value of the configuration property.
     * 
     * @return
     *     possible object is
     *     {@link Definitions.Configuration }
     *     
     */
    public Definitions.Configuration getConfiguration() {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Definitions.Configuration }
     *     
     */
    public void setConfiguration(Definitions.Configuration value) {
        this.configuration = value;
    }

    /**
     * Gets the value of the playerChoiceVariables property.
     * 
     * @return
     *     possible object is
     *     {@link Definitions.PlayerChoiceVariables }
     *     
     */
    public Definitions.PlayerChoiceVariables getPlayerChoiceVariables() {
        return playerChoiceVariables;
    }

    /**
     * Sets the value of the playerChoiceVariables property.
     * 
     * @param value
     *     allowed object is
     *     {@link Definitions.PlayerChoiceVariables }
     *     
     */
    public void setPlayerChoiceVariables(Definitions.PlayerChoiceVariables value) {
        this.playerChoiceVariables = value;
    }

    /**
     * Gets the value of the userStateVariables property.
     * 
     * @return
     *     possible object is
     *     {@link Definitions.UserStateVariables }
     *     
     */
    public Definitions.UserStateVariables getUserStateVariables() {
        return userStateVariables;
    }

    /**
     * Sets the value of the userStateVariables property.
     * 
     * @param value
     *     allowed object is
     *     {@link Definitions.UserStateVariables }
     *     
     */
    public void setUserStateVariables(Definitions.UserStateVariables value) {
        this.userStateVariables = value;
    }

    /**
     * Gets the value of the worldStateVariables property.
     * 
     * @return
     *     possible object is
     *     {@link Definitions.WorldStateVariables }
     *     
     */
    public Definitions.WorldStateVariables getWorldStateVariables() {
        return worldStateVariables;
    }

    /**
     * Sets the value of the worldStateVariables property.
     * 
     * @param value
     *     allowed object is
     *     {@link Definitions.WorldStateVariables }
     *     
     */
    public void setWorldStateVariables(Definitions.WorldStateVariables value) {
        this.worldStateVariables = value;
    }

    /**
     * Gets the value of the externalVariables property.
     * 
     * @return
     *     possible object is
     *     {@link Definitions.ExternalVariables }
     *     
     */
    public Definitions.ExternalVariables getExternalVariables() {
        return externalVariables;
    }

    /**
     * Sets the value of the externalVariables property.
     * 
     * @param value
     *     allowed object is
     *     {@link Definitions.ExternalVariables }
     *     
     */
    public void setExternalVariables(Definitions.ExternalVariables value) {
        this.externalVariables = value;
    }

    /**
     * Gets the value of the randomNumberGenerators property.
     * 
     * @return
     *     possible object is
     *     {@link Definitions.RandomNumberGenerators }
     *     
     */
    public Definitions.RandomNumberGenerators getRandomNumberGenerators() {
        return randomNumberGenerators;
    }

    /**
     * Sets the value of the randomNumberGenerators property.
     * 
     * @param value
     *     allowed object is
     *     {@link Definitions.RandomNumberGenerators }
     *     
     */
    public void setRandomNumberGenerators(Definitions.RandomNumberGenerators value) {
        this.randomNumberGenerators = value;
    }

    /**
     * Gets the value of the choicesToStateAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChoicesToStateAlgorithm() {
        return choicesToStateAlgorithm;
    }

    /**
     * Sets the value of the choicesToStateAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChoicesToStateAlgorithm(String value) {
        this.choicesToStateAlgorithm = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="Parameter" type="{}ParameterType"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Configuration {

        @XmlElement(name = "Parameter", required = true)
        protected ParameterType parameter;

        /**
         * Gets the value of the parameter property.
         * 
         * @return
         *     possible object is
         *     {@link ParameterType }
         *     
         */
        public ParameterType getParameter() {
            return parameter;
        }

        /**
         * Sets the value of the parameter property.
         * 
         * @param value
         *     allowed object is
         *     {@link ParameterType }
         *     
         */
        public void setParameter(ParameterType value) {
            this.parameter = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="PlayerChoiceVariable" type="{}ExternalDataType"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class ExternalVariables {

        @XmlElement(name = "PlayerChoiceVariable", required = true)
        protected ExternalDataType playerChoiceVariable;

        /**
         * Gets the value of the playerChoiceVariable property.
         * 
         * @return
         *     possible object is
         *     {@link ExternalDataType }
         *     
         */
        public ExternalDataType getPlayerChoiceVariable() {
            return playerChoiceVariable;
        }

        /**
         * Sets the value of the playerChoiceVariable property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExternalDataType }
         *     
         */
        public void setPlayerChoiceVariable(ExternalDataType value) {
            this.playerChoiceVariable = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="PlayerChoiceVariable" type="{}dataType"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class PlayerChoiceVariables {

        @XmlElement(name = "PlayerChoiceVariable", required = true)
        protected DataType playerChoiceVariable;

        /**
         * Gets the value of the playerChoiceVariable property.
         * 
         * @return
         *     possible object is
         *     {@link DataType }
         *     
         */
        public DataType getPlayerChoiceVariable() {
            return playerChoiceVariable;
        }

        /**
         * Sets the value of the playerChoiceVariable property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataType }
         *     
         */
        public void setPlayerChoiceVariable(DataType value) {
            this.playerChoiceVariable = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="RandomNumberGenerator" type="{}RandomNumberGeneratorType"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class RandomNumberGenerators {

        @XmlElement(name = "RandomNumberGenerator", required = true)
        protected RandomNumberGeneratorType randomNumberGenerator;

        /**
         * Gets the value of the randomNumberGenerator property.
         * 
         * @return
         *     possible object is
         *     {@link RandomNumberGeneratorType }
         *     
         */
        public RandomNumberGeneratorType getRandomNumberGenerator() {
            return randomNumberGenerator;
        }

        /**
         * Sets the value of the randomNumberGenerator property.
         * 
         * @param value
         *     allowed object is
         *     {@link RandomNumberGeneratorType }
         *     
         */
        public void setRandomNumberGenerator(RandomNumberGeneratorType value) {
            this.randomNumberGenerator = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="UserStateVariable" type="{}dataType"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class UserStateVariables {

        @XmlElement(name = "UserStateVariable", required = true)
        protected DataType userStateVariable;

        /**
         * Gets the value of the userStateVariable property.
         * 
         * @return
         *     possible object is
         *     {@link DataType }
         *     
         */
        public DataType getUserStateVariable() {
            return userStateVariable;
        }

        /**
         * Sets the value of the userStateVariable property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataType }
         *     
         */
        public void setUserStateVariable(DataType value) {
            this.userStateVariable = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="WorldStateVariable" type="{}dataType"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class WorldStateVariables {

        @XmlElement(name = "WorldStateVariable", required = true)
        protected DataType worldStateVariable;

        /**
         * Gets the value of the worldStateVariable property.
         * 
         * @return
         *     possible object is
         *     {@link DataType }
         *     
         */
        public DataType getWorldStateVariable() {
            return worldStateVariable;
        }

        /**
         * Sets the value of the worldStateVariable property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataType }
         *     
         */
        public void setWorldStateVariable(DataType value) {
            this.worldStateVariable = value;
        }

    }

}
