//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.27 at 05:23:59 PM EEST 
//


package gr.aua.simbug.definition;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Configuration">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="Parameter" type="{}ParameterType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PlayerChoiceVariables">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="PlayerChoiceVariable" type="{}VariableType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UserStateVariables">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="UserStateVariable" type="{}UserStateVariableDataType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="WorldStateVariables">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="WorldStateVariable" type="{}VariableType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ExternalVariables" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="ExternalVariable" type="{}ExternalDataType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RandomNumberGenerators">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="RandomNumberGenerator" type="{}RandomNumberGeneratorType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ChoicesToStateAlgorithm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "Definition")
public class Definition {

    @XmlElement(name = "Configuration", required = true)
    protected Definition.Configuration configuration;
    @XmlElement(name = "PlayerChoiceVariables", required = true)
    protected Definition.PlayerChoiceVariables playerChoiceVariables;
    @XmlElement(name = "UserStateVariables", required = true)
    protected Definition.UserStateVariables userStateVariables;
    @XmlElement(name = "WorldStateVariables", required = true)
    protected Definition.WorldStateVariables worldStateVariables;
    @XmlElement(name = "ExternalVariables")
    protected Definition.ExternalVariables externalVariables;
    @XmlElement(name = "RandomNumberGenerators", required = true)
    protected Definition.RandomNumberGenerators randomNumberGenerators;
    @XmlElement(name = "ChoicesToStateAlgorithm", required = true)
    protected String choicesToStateAlgorithm;

	@Override
	public String toString() {
		String s= super.toString();
		s += "\n"+"# PlayerChoicesVariables = " + this.getPlayerChoiceVariables().playerChoiceVariable.size();
		s += "\n"+"# UserStateVariables = " + this.getUserStateVariables().getUserStateVariable().size();
		return s;
	}
    
    /**
     * Gets the value of the configuration property.
     * 
     * @return
     *     possible object is
     *     {@link Definition.Configuration }
     *     
     */
    public Definition.Configuration getConfiguration() {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Definition.Configuration }
     *     
     */
    public void setConfiguration(Definition.Configuration value) {
        this.configuration = value;
    }

    /**
     * Gets the value of the playerChoiceVariables property.
     * 
     * @return
     *     possible object is
     *     {@link Definition.PlayerChoiceVariables }
     *     
     */
    public Definition.PlayerChoiceVariables getPlayerChoiceVariables() {
        return playerChoiceVariables;
    }

    /**
     * Sets the value of the playerChoiceVariables property.
     * 
     * @param value
     *     allowed object is
     *     {@link Definition.PlayerChoiceVariables }
     *     
     */
    public void setPlayerChoiceVariables(Definition.PlayerChoiceVariables value) {
        this.playerChoiceVariables = value;
    }

    /**
     * Gets the value of the userStateVariables property.
     * 
     * @return
     *     possible object is
     *     {@link Definition.UserStateVariables }
     *     
     */
    public Definition.UserStateVariables getUserStateVariables() {
        return userStateVariables;
    }

    /**
     * Sets the value of the userStateVariables property.
     * 
     * @param value
     *     allowed object is
     *     {@link Definition.UserStateVariables }
     *     
     */
    public void setUserStateVariables(Definition.UserStateVariables value) {
        this.userStateVariables = value;
    }

    /**
     * Gets the value of the worldStateVariables property.
     * 
     * @return
     *     possible object is
     *     {@link Definition.WorldStateVariables }
     *     
     */
    public Definition.WorldStateVariables getWorldStateVariables() {
        return worldStateVariables;
    }

    /**
     * Sets the value of the worldStateVariables property.
     * 
     * @param value
     *     allowed object is
     *     {@link Definition.WorldStateVariables }
     *     
     */
    public void setWorldStateVariables(Definition.WorldStateVariables value) {
        this.worldStateVariables = value;
    }

    /**
     * Gets the value of the externalVariables property.
     * 
     * @return
     *     possible object is
     *     {@link Definition.ExternalVariables }
     *     
     */
    public Definition.ExternalVariables getExternalVariables() {
        return externalVariables;
    }

    /**
     * Sets the value of the externalVariables property.
     * 
     * @param value
     *     allowed object is
     *     {@link Definition.ExternalVariables }
     *     
     */
    public void setExternalVariables(Definition.ExternalVariables value) {
        this.externalVariables = value;
    }

    /**
     * Gets the value of the randomNumberGenerators property.
     * 
     * @return
     *     possible object is
     *     {@link Definition.RandomNumberGenerators }
     *     
     */
    public Definition.RandomNumberGenerators getRandomNumberGenerators() {
        return randomNumberGenerators;
    }

    /**
     * Sets the value of the randomNumberGenerators property.
     * 
     * @param value
     *     allowed object is
     *     {@link Definition.RandomNumberGenerators }
     *     
     */
    public void setRandomNumberGenerators(Definition.RandomNumberGenerators value) {
        this.randomNumberGenerators = value;
    }

    /**
     * Gets the value of the choicesToStateAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChoicesToStateAlgorithm() {
        return choicesToStateAlgorithm;
    }

    /**
     * Sets the value of the choicesToStateAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChoicesToStateAlgorithm(String value) {
        this.choicesToStateAlgorithm = value;
    }
    



    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="Parameter" type="{}ParameterType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "parameter"
    })
    public static class Configuration {

        @XmlElement(name = "Parameter")
        protected List<ParameterType> parameter;

        /**
         * Gets the value of the parameter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the parameter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParameter().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ParameterType }
         * 
         * 
         */
        public List<ParameterType> getParameter() {
            if (parameter == null) {
                parameter = new ArrayList<ParameterType>();
            }
            return this.parameter;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="ExternalVariable" type="{}ExternalDataType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "externalVariable"
    })
    public static class ExternalVariables {

        @XmlElement(name = "ExternalVariable")
        protected List<ExternalDataType> externalVariable;

        /**
         * Gets the value of the externalVariable property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the externalVariable property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExternalVariable().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ExternalDataType }
         * 
         * 
         */
        public List<ExternalDataType> getExternalVariable() {
            if (externalVariable == null) {
                externalVariable = new ArrayList<ExternalDataType>();
            }
            return this.externalVariable;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="PlayerChoiceVariable" type="{}VariableType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "playerChoiceVariable"
    })
    public static class PlayerChoiceVariables {

        @XmlElement(name = "PlayerChoiceVariable")
        protected List<VariableType> playerChoiceVariable;

        /**
         * Gets the value of the playerChoiceVariable property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the playerChoiceVariable property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPlayerChoiceVariable().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link VariableType }
         * 
         * 
         */
        public List<VariableType> getPlayerChoiceVariable() {
            if (playerChoiceVariable == null) {
                playerChoiceVariable = new ArrayList<VariableType>();
            }
            return this.playerChoiceVariable;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="RandomNumberGenerator" type="{}RandomNumberGeneratorType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "randomNumberGenerator"
    })
    public static class RandomNumberGenerators {

        @XmlElement(name = "RandomNumberGenerator")
        protected List<RandomNumberGeneratorType> randomNumberGenerator;

        /**
         * Gets the value of the randomNumberGenerator property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the randomNumberGenerator property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRandomNumberGenerator().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RandomNumberGeneratorType }
         * 
         * 
         */
        public List<RandomNumberGeneratorType> getRandomNumberGenerator() {
            if (randomNumberGenerator == null) {
                randomNumberGenerator = new ArrayList<RandomNumberGeneratorType>();
            }
            return this.randomNumberGenerator;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="UserStateVariable" type="{}UserStateVariableDataType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userStateVariable"
    })
    public static class UserStateVariables {

        @XmlElement(name = "UserStateVariable")
        protected List<UserStateVariableDataType> userStateVariable;

        /**
         * Gets the value of the userStateVariable property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the userStateVariable property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUserStateVariable().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UserStateVariableDataType }
         * 
         * 
         */
        public List<UserStateVariableDataType> getUserStateVariable() {
            if (userStateVariable == null) {
                userStateVariable = new ArrayList<UserStateVariableDataType>();
            }
            return this.userStateVariable;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="WorldStateVariable" type="{}VariableType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "worldStateVariable"
    })
    public static class WorldStateVariables {

        @XmlElement(name = "WorldStateVariable")
        protected List<VariableType> worldStateVariable;

        /**
         * Gets the value of the worldStateVariable property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the worldStateVariable property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getWorldStateVariable().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link VariableType }
         * 
         * 
         */
        public List<VariableType> getWorldStateVariable() {
            if (worldStateVariable == null) {
                worldStateVariable = new ArrayList<VariableType>();
            }
            return this.worldStateVariable;
        }

    } 
    

}
