//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.18 at 01:51:09 AM EEST 
//


package gr.aua.simbug.definition;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gr.aua.simbug.definition package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gr.aua.simbug.definition
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExternalDataType }
     * 
     */
    public ExternalDataType createExternalDataType() {
        return new ExternalDataType();
    }

    /**
     * Create an instance of {@link Definitions.UserStateVariables }
     * 
     */
    public Definitions.UserStateVariables createDefinitionsUserStateVariables() {
        return new Definitions.UserStateVariables();
    }

    /**
     * Create an instance of {@link Definitions.ExternalVariables }
     * 
     */
    public Definitions.ExternalVariables createDefinitionsExternalVariables() {
        return new Definitions.ExternalVariables();
    }

    /**
     * Create an instance of {@link Definitions.PlayerChoiceVariables }
     * 
     */
    public Definitions.PlayerChoiceVariables createDefinitionsPlayerChoiceVariables() {
        return new Definitions.PlayerChoiceVariables();
    }

    /**
     * Create an instance of {@link Definitions.Configuration }
     * 
     */
    public Definitions.Configuration createDefinitionsConfiguration() {
        return new Definitions.Configuration();
    }

    /**
     * Create an instance of {@link RandomNumberGeneratorType }
     * 
     */
    public RandomNumberGeneratorType createRandomNumberGeneratorType() {
        return new RandomNumberGeneratorType();
    }

    /**
     * Create an instance of {@link Definitions.WorldStateVariables }
     * 
     */
    public Definitions.WorldStateVariables createDefinitionsWorldStateVariables() {
        return new Definitions.WorldStateVariables();
    }

    /**
     * Create an instance of {@link ParameterType }
     * 
     */
    public ParameterType createParameterType() {
        return new ParameterType();
    }

    /**
     * Create an instance of {@link VariableType }
     * 
     */
    public VariableType createVariableType() {
        return new VariableType();
    }

    /**
     * Create an instance of {@link Definitions }
     * 
     */
    public Definitions createDefinitions() {
        return new Definitions();
    }

    /**
     * Create an instance of {@link Definitions.RandomNumberGenerators }
     * 
     */
    public Definitions.RandomNumberGenerators createDefinitionsRandomNumberGenerators() {
        return new Definitions.RandomNumberGenerators();
    }

}
