//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.27 at 05:23:59 PM EEST 
//


package gr.aua.simbug.definition;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gr.aua.simbug.definition package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gr.aua.simbug.definition
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Definition.ExternalVariables }
     * 
     */
    public Definition.ExternalVariables createDefinitionsExternalVariables() {
        return new Definition.ExternalVariables();
    }

    /**
     * Create an instance of {@link Definition.PlayerChoiceVariables }
     * 
     */
    public Definition.PlayerChoiceVariables createDefinitionsPlayerChoiceVariables() {
        return new Definition.PlayerChoiceVariables();
    }

    /**
     * Create an instance of {@link Definition }
     * 
     */
    public Definition createDefinitions() {
        return new Definition();
    }

    /**
     * Create an instance of {@link Definition.WorldStateVariables }
     * 
     */
    public Definition.WorldStateVariables createDefinitionsWorldStateVariables() {
        return new Definition.WorldStateVariables();
    }

    /**
     * Create an instance of {@link RandomNumberGeneratorType }
     * 
     */
    public RandomNumberGeneratorType createRandomNumberGeneratorType() {
        return new RandomNumberGeneratorType();
    }

    /**
     * Create an instance of {@link Definition.Configuration }
     * 
     */
    public Definition.Configuration createDefinitionsConfiguration() {
        return new Definition.Configuration();
    }

    /**
     * Create an instance of {@link ExternalDataType }
     * 
     */
    public ExternalDataType createExternalDataType() {
        return new ExternalDataType();
    }

    /**
     * Create an instance of {@link ParameterType }
     * 
     */
    public ParameterType createParameterType() {
        return new ParameterType();
    }

    /**
     * Create an instance of {@link Definition.RandomNumberGenerators }
     * 
     */
    public Definition.RandomNumberGenerators createDefinitionsRandomNumberGenerators() {
        return new Definition.RandomNumberGenerators();
    }

    /**
     * Create an instance of {@link UserStateVariableDataType }
     * 
     */
    public UserStateVariableDataType createUserStateVariableDataType() {
        return new UserStateVariableDataType();
    }

    /**
     * Create an instance of {@link Definition.UserStateVariables }
     * 
     */
    public Definition.UserStateVariables createDefinitionsUserStateVariables() {
        return new Definition.UserStateVariables();
    }

    /**
     * Create an instance of {@link VariableType }
     * 
     */
    public VariableType createVariableType() {
        return new VariableType();
    }

}
