//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.27 at 05:23:59 PM EEST 
//


package gr.aua.simbug.definition;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserStateVariableDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserStateVariableDataType">
 *   &lt;complexContent>
 *     &lt;extension base="{}VariableType">
 *       &lt;sequence>
 *         &lt;element name="WorldVisible" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserStateVariableDataType", propOrder = {
    "worldVisible"
})
public class UserStateVariableDataType
    extends VariableType
{

    @XmlElement(name = "WorldVisible", defaultValue = "false")
    protected Boolean worldVisible;

    /**
     * Gets the value of the worldVisible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWorldVisible() {
        return worldVisible;
    }

    /**
     * Sets the value of the worldVisible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWorldVisible(Boolean value) {
        this.worldVisible = value;
    }

}
