//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.07 at 03:14:52 PM EEST 
//


package gr.aua.simbug.definition;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gr.aua.simbug.definition package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gr.aua.simbug.definition
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Definition }
     * 
     */
    public Definition createDefinition() {
        return new Definition();
    }

    /**
     * Create an instance of {@link Definition.Configuration }
     * 
     */
    public Definition.Configuration createDefinitionConfiguration() {
        return new Definition.Configuration();
    }

    /**
     * Create an instance of {@link Definition.PlayerChoiceVariables }
     * 
     */
    public Definition.PlayerChoiceVariables createDefinitionPlayerChoiceVariables() {
        return new Definition.PlayerChoiceVariables();
    }

    /**
     * Create an instance of {@link Definition.PlayerStateVariables }
     * 
     */
    public Definition.PlayerStateVariables createDefinitionPlayerStateVariables() {
        return new Definition.PlayerStateVariables();
    }

    /**
     * Create an instance of {@link Definition.WorldStateVariables }
     * 
     */
    public Definition.WorldStateVariables createDefinitionWorldStateVariables() {
        return new Definition.WorldStateVariables();
    }

    /**
     * Create an instance of {@link Definition.ExternalParameters }
     * 
     */
    public Definition.ExternalParameters createDefinitionExternalParameters() {
        return new Definition.ExternalParameters();
    }

    /**
     * Create an instance of {@link Definition.RandomNumberGenerators }
     * 
     */
    public Definition.RandomNumberGenerators createDefinitionRandomNumberGenerators() {
        return new Definition.RandomNumberGenerators();
    }

    /**
     * Create an instance of {@link PlayerStateVariableDataType }
     * 
     */
    public PlayerStateVariableDataType createPlayerStateVariableDataType() {
        return new PlayerStateVariableDataType();
    }

    /**
     * Create an instance of {@link ParameterType }
     * 
     */
    public ParameterType createParameterType() {
        return new ParameterType();
    }

    /**
     * Create an instance of {@link ExternalDataType }
     * 
     */
    public ExternalDataType createExternalDataType() {
        return new ExternalDataType();
    }

    /**
     * Create an instance of {@link VariableType }
     * 
     */
    public VariableType createVariableType() {
        return new VariableType();
    }

    /**
     * Create an instance of {@link RandomNumberGeneratorType }
     * 
     */
    public RandomNumberGeneratorType createRandomNumberGeneratorType() {
        return new RandomNumberGeneratorType();
    }

}
